spring.application.name=ms-competition-reg
server.port=8094

spring.datasource.url=jdbc:mysql://localhost:3306/db_competition?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=clave_secreta_carmeet_2026_muy_segura__123456789

spring.flyway.baseline-on-migrate=true

# URLs de microservicios para WebClient
services.event-core.base-url=http://localhost:8082
services.vehicle-registry.base-url=http://localhost:8086
services.notification-log.base-url=http://localhost:8085
