ALTER TABLE ticket ADD COLUMN categoria VARCHAR(255);
ALTER TABLE ticket MODIFY COLUMN estado VARCHAR(255) NULL;
ALTER TABLE ticket MODIFY COLUMN username VARCHAR(255) NULL;
ALTER TABLE beneficio ADD COLUMN nombre VARCHAR(255);
