spring.application.name=ms-gateway
server.port=${PORT:8777}

# ms-auth-user
spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth-user
spring.cloud.gateway.server.webmvc.routes[0].uri=${AUTH_USER_URL:lb://ms-auth-user}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

# ms-event-core
spring.cloud.gateway.server.webmvc.routes[1].id=ms-event-core
spring.cloud.gateway.server.webmvc.routes[1].uri=${EVENT_CORE_URL:lb://ms-event-core}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/eventos/**

# ms-vehicle-registry
spring.cloud.gateway.server.webmvc.routes[2].id=ms-vehicle-registry
spring.cloud.gateway.server.webmvc.routes[2].uri=${VEHICLE_REGISTRY_URL:lb://ms-vehicle-registry}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/vehiculos/**

# ms-ticketing
spring.cloud.gateway.server.webmvc.routes[3].id=ms-ticketing
spring.cloud.gateway.server.webmvc.routes[3].uri=${TICKETING_URL:lb://ms-ticketing}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/tickets/**

# ms-competition-reg
spring.cloud.gateway.server.webmvc.routes[4].id=ms-competition-reg
spring.cloud.gateway.server.webmvc.routes[4].uri=${COMPETITION_REG_URL:lb://ms-competition-reg}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/inscripciones/**

# ms-live-scoreboard
spring.cloud.gateway.server.webmvc.routes[5].id=ms-live-scoreboard
spring.cloud.gateway.server.webmvc.routes[5].uri=${LIVE_SCOREBOARD_URL:lb://ms-live-scoreboard}
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/puntuaciones/**

# ms-venue-capacity
spring.cloud.gateway.server.webmvc.routes[6].id=ms-venue-capacity
spring.cloud.gateway.server.webmvc.routes[6].uri=${VENUE_CAPACITY_URL:lb://ms-venue-capacity}
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/recintos/**

# ms-payment-mock
spring.cloud.gateway.server.webmvc.routes[7].id=ms-payment-mock
spring.cloud.gateway.server.webmvc.routes[7].uri=${PAYMENT_MOCK_URL:lb://ms-payment-mock}
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/pagos/**

# ms-analytics-report
spring.cloud.gateway.server.webmvc.routes[8].id=ms-analytics-report
spring.cloud.gateway.server.webmvc.routes[8].uri=${ANALYTICS_REPORT_URL:lb://ms-analytics-report}
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/v1/reportes/**

# ms-notification-log
spring.cloud.gateway.server.webmvc.routes[9].id=ms-notification-log
spring.cloud.gateway.server.webmvc.routes[9].uri=${NOTIFICATION_LOG_URL:lb://ms-notification-log}
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/v1/notificaciones/**

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
