ALTER TABLE reporte ADD COLUMN IF NOT EXISTS evento_id BIGINT;
ALTER TABLE reporte ADD COLUMN IF NOT EXISTS total_tickets INT DEFAULT 0;
ALTER TABLE reporte ADD COLUMN IF NOT EXISTS total_inscripciones INT DEFAULT 0;
