spring.application.name=ms-venue-capacity
server.port=8096

spring.datasource.url=jdbc:mysql://localhost:3306/db_venue
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

jwt.secret=clave_secreta_carmeet_2026_muy_segura__123456789
